### ISSUE TITLE
Remove 2.10 build

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/blaze#129]
Looks like it was dropped from http4s as of the 0.17 series.

**Comment by rossabaker** [comment]
Yes, because there is no fs2 for 2.10.

There's no need to drop it if it's not causing pain, but http4s core doesn't need it anymore.

**Comment by bryce-anderson** [comment]
It's annoying me only for workflow reasons. I don't plan on doing it until the new HTTP/2 stuff is in master. In the meantime, opinions welcome.

If anybody wants to keep the 2.10 build around, I'm fine with that.

**Comment by rossabaker** [comment]
I am an outlier in supporting old versions.  (We still have a lot of 2.10 at $work.)  If it's causing friction, and nobody is volunteering (I'm not), then kill it.

**Comment by bryce-anderson** [comment]
Done via 7629216b55523ff344bd3c9cdf90481bef16b8c3.
