### ISSUE TITLE
Add Keep-Alive

### ISSUE THREAD

**Issue by chtefi** [http4s/blaze#172]
Hey,

We noticed http4s always opened connections on new ports (note: it's behind a load-balancer here). We thought of using keep-alive (at the TCP level) to introduce sockets reutilization but found no option to enable it in http4s/blaze. 

Looking at the source, we didn't find anything related to keep-alive; something along the line
`socketChannel.setOption(StandardSocketOptions.SO_KEEPALIVE, true);` when we `.accept` the connection.

What do you think? Do you want a PR to always force it or make it an option? Or any particular reason to not do it?

Thanks for your help!

edit: Actually I found out that it would be possible to pass the option using the `ChannelOptions` (the default contains only `TCP_NODELAY`), but can't find my way to pass them from http4s; still looking.

**Comment by bryce-anderson** [comment]
I think it should absolutely be configurable. There is already a mechanism for this: `ChannelOptions`, but I suspect it's underutilized, and perhaps awkward. I haven't toyed with that in a while, I've been busy working on the new http2 client and server implementations (which were just merged into master!).

If you don't mind, I have some questions about how you're using blaze.
From the sound of it, you're using this on the server side. Are you using nio1 or nio2? Are you using blaze through the http4s project, or directly? (it needs to be configurable in blaze either way, it just needs to be configurable in two places if you're using it through http4s).

**Comment by chtefi** [comment]
I'm using http4s with nio1 and ChannelOptions is not "reachable" through the BlazeBuilder.
Actually, we could just modify https://github.com/http4s/http4s/blob/master/blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala#L220 and add a 3rd parameter which are the `ChannelOptions` (fallback to the default right now because unspecified). Do you want me to open an issue over there instead?

**Comment by bryce-anderson** [comment]
Yeah, sounds like http4s proper is where the patch will have to be, so fft open a ticket there. Thanks for reporting it!

**Comment by chtefi** [comment]
Thanks @bryce-anderson, done.

**Comment by resolve123** [comment]
how to set keep-alive for blazeServer. In production my connections between application and load balancer are getting broken.
