### ISSUE TITLE
Add scalastyle to the build

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/blaze#174]
Now that everything is in master it might be a good time to conform to some sort of style.

**Comment by rossabaker** [comment]
scalastyle or scalafmt? http4s uses the latter. I poked at the former.
They're complementary, I think.

**Comment by bryce-anderson** [comment]
Both really, because as you noted, they're complementary. I'll open another issue for scalafmt.

**Comment by rossabaker** [comment]
http4s flirted with this but never added it.  Maybe it makes sense there, too.  Is there anything in particular you're looking to get out of it?

**Comment by bryce-anderson** [comment]
Not particularly. I just found it nice for pointing out things like `return` statements etc. I don't want to make compile or test results predicated on it. At least not right now.
