### ISSUE TITLE
Blaze `SelectorLoop.scala` Catches Fatal Exceptions

### ISSUE THREAD

**Issue by zmccoy** [http4s/blaze#209]
The `run` method in `SelectLoop.scala` catches the Throwable and then just logs.  For OOMs this results in the log being outputted and the OOM error stopping there.  This happens here https://github.com/http4s/blaze/blob/v0.12.13/core/src/main/scala/org/http4s/blaze/channel/nio1/SelectorLoop.scala#L156.  I'd like to fix this once I know the correct direction http4s wants.  

Would the right course of action be to log and then rethrow the Throwable up to kill the process?

**Comment by bryce-anderson** [comment]
Do we materially benefit from rethrowing? I don't think rethrowing will directly lead to killing the process, just the thread. I'm a little concerned about not catching things that are non-fatal but don't get caught in NonFatal. We do catch the exception again outside of the loop (probably not great) and shutdown the selector.
