### ISSUE TITLE
Bug when status code is not followed by a description

### ISSUE THREAD

**Issue by aaubert** [http4s/blaze#29]
I have noticed that when a server returns a status code "200" the parser Http1ClientParser throws the following exception because it expects "200 OK".

org.http4s.blaze.http.http_parser.BaseExceptions$BadResponse: Response lacks status Reason: Response lacks status Reason

As the status codes are standardized and "200" will always mean "OK", wouldn't it make sense to have a more flexible parser which could accept status code without description?

**Comment by refried** [comment]
based on rfc2616 section 6.1, I think “the associated textual phrase” is part of the spec, unfortunately.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html

**Comment by refried** [comment]
Where are you getting that truncated response from btw?

**Comment by bryce-anderson** [comment]
Well in [rfc7230 Section 3.1.2](https://tools.ietf.org/html/rfc7230#section-3.1.2) the `reason-phrase` is defined as:
```reason-phrase  = *( HTAB / SP / VCHAR / obs-text )```

and [rfc2616 6.1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html) it is 
```Reason-Phrase  = *<TEXT, excluding CR, LF>```

which suggests that its not actually required. It does seem like a bug.

**Comment by aaubert** [comment]
Thank you, Bryce, for those references. In both texts, it is said that the description is meant only for human-readability.

"A client SHOULD ignore the reason-phrase content."

"The Status-Code is intended for use by automata and the Reason-Phrase is intended for the human user. The client is not required to examine or display the Reason- Phrase."

**Comment by aaubert** [comment]
To answer your question, Arya, I get this behavior from a REST API on Elemental Server (a transcoding server from ElementalTechnologies), but it is probably not the only product with such behaviour.

**Comment by bryce-anderson** [comment]
@aaubert yes, but just because they are only meant for humans doesn't means it isn't required. However, in this case, its not required :smile:. Are you interested in putting a PR for this? Otherwise I'll take care of it when I find some time.

**Comment by aaubert** [comment]
I will try to do a bugfix this week.

**Comment by bryce-anderson** [comment]
@aaubert: cool, thank you. 
In my minds eye I imagine this section of code https://github.com/http4s/blaze/blob/master/http/src/main/java/org/http4s/blaze/http/http_parser/Http1ClientParser.java#L175-L182 getting turned into a private function that gets called early if `LF` is found in the `SPACE2` section.

**Comment by refried** [comment]
My bad, sorry.

@bryce-anderson Do you think the SP between the code and the CRLF is required? :grinning:

**Comment by bryce-anderson** [comment]
@refried, I think rechnically yes: (rfc7230)
```status-line = HTTP-version SP status-code SP reason-phrase CRLF```
but I wouldn't be surprised if its typically dropped. I think it might be worth looking at netty or other parsers to see how they handle this.

**Comment by refried** [comment]
I'm fine with dropping it.

**Comment by rossabaker** [comment]
+1.  "Be strict in what you emit, be generous in what you parse."

**Comment by bryce-anderson** [comment]
@aaubert, when you make your PR, could you please target the release-0.10.1 branch?

**Comment by aaubert** [comment]
I did a bugfix, but I want to ask your opinions before pushing.

At the end of the parsing, the abstract method "submitResponseLine" is called with the value of the reason ( https://github.com/http4s/blaze/blob/master/http/src/main/java/org/http4s/blaze/http/http_parser/Http1ClientParser.java#L46 ). Depending on the reason value given to this method, it might have different impacts on the subclasses.

I considered three solutions
1. A dummy value for reason (null, empty or the code value)
2. Mapping the code to the reason according to the specifications
3. Having a second method "submitResponseLine" without the reason

For now, I have chosen to set a null value to the reason.

When looking at the method implementation in the subclass ( https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/BlazeHttp1ClientParser.scala#L44-L49 ), I have noticed that if the reason does not match exactly (even case-sensitive!) the specifications, it will create a new Status object each time ( https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/Status.scala#L65-L68 ), so I am thinking to modify BlazeHttp1ClientParser with a "if reason is null then call Status.fromInt instead of Status.fromIntAndReason". This will avoid creating an object for each http call and will "recover" a value for the reason.

Any thoughts?

**Comment by bryce-anderson** [comment]
I would just go with what it is: an empty string. I'd rather avoid null. If
we want we can check for an empty string and use for code to get a status.

**Comment by aaubert** [comment]
I did the bugfix with giving an empty string as the reason-phrase when it is missing.

I also did a small fix for the subclass in the http4s project to prevent instantiating a Status each time an empty reason-phrase is received. I will do a PR for that on the http4s project. Could someone create a "release-0.11.3" branch on that project?

**Comment by bryce-anderson** [comment]
@aaubert, the branch is in http4s now.

**Comment by refried** [comment]
> If we want, we can check for an empty string and use the code to get a status.

I hope no one has to do this :-\  But maybe no one does.

**Comment by aaubert** [comment]
Would it be possible to have the v0.10.1-SNAPSHOT in the Sonatype repository or to release the v0.10.1 in Maven Central (or to merge the fix into the v0.11.0-SNAPSHOT) ?

**Comment by bryce-anderson** [comment]
@aaubert, v0.10.1 should be on its way to Maven Central. Thanks again for the fix.
