### ISSUE TITLE
Release new version of blaze and http4s?

### ISSUE THREAD

**Issue by anilkumarmyla** [http4s/blaze#397]
We're using conscrypt (ssl provider) and see a file descriptor leak when using with http4s - blaze v0.14.11 and http4s 0.21.3, however rebuilding blaze with current master and using it fixes the issue (possibly due to #386 ).

**Comment by rossabaker** [comment]
Sorry it took a week before I saw this.  I didn't realize that was such a useful fix.  I'll cut a blaze release now.  It will be binary compatible, so you can manually bump that until we release http4s again, but we'll work toward that quickly as well.

**Comment by rossabaker** [comment]
blaze-0.14.12 is on its way to Maven Central now.  Please let me know if it works, and we'll get an http4s patch release ready.

**Comment by anilkumarmyla** [comment]
I was a bit premature when I claimed it fixed our file descriptor issue, but seems it did not. For now, please follow the normal release cycle for http4s
