### ISSUE TITLE
ALPNServerSelector clarification

### ISSUE THREAD

**Issue by vasilmkd** [http4s/blaze#521]
Hello. I've been investigating the following [issue](https://github.com/http4s/http4s/issues/4707) in `http4s`. Diving into the problem has seemingly led me to the `ALPNServerSelector`.

Namely, no accepted HTTP/2 protocols are being returned to `http4s` and therefore no HTTP/2 traffic is being served. I cloned the `blaze` project and added some logging statements and it seems like the registered `ALPN.ServerProvider` is not called at all by the ALPN machinery. I verified that the `ServerProvider` is in fact properly registered, just never called.

Furthermore, it seems like the whole `ALPN.ServerProvider` implementation does not respect the contract that ALPN requires and probably results in a memory leak. The `ServerProvider` would never be unregistered even if called. Here is an [example](https://xy2401.com/local-docs/java/jetty.9.4.24.v20191120/alpn-chapter.html#alpn-openjdk8-server-example) of a proper implementation.

Are these legitimate issues or is there something else going on? Thank you.

I'm using AdoptOpenJDK 11.0.10 and Scala 2.13.5 on MacOS 11.2.3, if this helps anything.

Edit: No difference when using AdoptOpenJDK 1.8.0_u282.

**Comment by vasilmkd** [comment]
According to [this](https://webtide.com/jetty-alpn-java-8u252/), the ALPN API might not be usable on Java 8u252 and later because the platform APIs take precedence.

**Comment by rossabaker** [comment]
If we fix this for http4s-0.21, we'd need to do it down on series/0.14.x here.  If we don't, a main patch here, and it'll be ready for http4s >= 0.22.

**Comment by rossabaker** [comment]
Or a copy of the selector could be moved into the http4s repo if we don't want to dust off blaze-0.14.

**Comment by vasilmkd** [comment]
Fixed by #522.
