### ISSUE TITLE
PooledHttp1Client hangs indefinitely

### ISSUE THREAD

**Issue by tindzk** [http4s/blaze#54]
If too many parallel connections are opened, `PooledHttp1Client` may hang indefinitely:

```scala
import scalaz.concurrent.Task

import org.http4s.EntityDecoder._
import org.http4s.client.blaze.PooledHttp1Client
import org.http4s.client.middleware.FollowRedirect

val urls = List(
  "https://t.co/SgvG70x3yi",
  "https://t.co/IiL4JQBbRe",
  "https://t.co/8BPeJi0QcU",
  "https://t.co/bbBYDJ3H7f",
  "https://t.co/6vvLhfqmIZ",
  "https://t.co/SgvG70x3yi",
  "https://t.co/IiL4JQBbRe",
  "https://t.co/iBeFSQEWjO",
  "https://t.co/f8jz2pGAZn",
  "https://t.co/WrU8l1me7G"
)

val httpClient = FollowRedirect(5)(PooledHttp1Client())
val requests =
  Task.gatherUnordered(
    urls.map(httpClient.expect(_)(text).attempt)
  ).unsafePerformSync

println(requests)
```

If I use `SimpleHttp1Client` instead, it works flawlessly.

**Comment by bryce-anderson** [comment]
Generally speaking, its not safe to `.unsafePerformSync` without risking a deadlock on the executing threads. This one seems a bit odd as its only blocking at the very end. Do you mind adding a `Task.fork` about your sync call and seeing what happens?

If we need to continue this, lets do it in the http4s/http4s project.
Btw, thanks for the nice example. 😄
