### ISSUE TITLE
Obtaining redirected location

### ISSUE THREAD

**Issue by tindzk** [http4s/blaze#55]
I would like to obtain the location a website redirects to. I came up with the following workaround, which unfortunately requires mutation:

```scala
def resolveRedirect(url: String, redirects: Int = 5): Task[Option[String]] = {
  val httpClient = SimpleHttp1Client()
  var resolvedUrl = Option.empty[String]

  def wrapClient(client: Client): Client = {
    def prepareLoop(req: Request): Task[DisposableResponse] = {
      resolvedUrl = Some(req.uri.renderString)
      client.open(req).attempt.flatMap {
        case \/-(dr) => Task.now(dr)
        case -\/(e)  => Task.fail(e)
      }
    }

    client.copy(open = Service.lift(prepareLoop))
  }

  val client = FollowRedirect(redirects)(wrapClient(httpClient))

  import org.http4s.EntityDecoder._
  client.expect(url)(text).attempt.map {
    case \/-(dr) => resolvedUrl
    case -\/(e)  => None
  }
}
```

Another downside is that `attempt` fetches the response even though we could close the connection after the HTTP headers were read.

**Comment by reactormonk** [comment]
Shouldn't this be a stackoverflow question?

**Comment by tindzk** [comment]
Perhaps. This was meant to be a feature request to make the redirected request accessible in `expect`.

**Comment by reactormonk** [comment]
I don't think that's possible. You might have to write your own `FollowRedirect` combinator, which has its own `expect`, which gives you a `Task[(T, Location)]`.

**Comment by rossabaker** [comment]
Yeah, I think FollowRedirect is not quite right here.  I would issue a HEAD request to the original Uri.  If you get a 3xx response with a `Location` header, loop.  If you get a non-3xx response, you're done.  This assumes that every step along the way handles a HEAD identical to a GET with a discarded body.  If you can't assume that, issue GETs, and be prepared to discard the body.

**Comment by bryce-anderson** [comment]
Hi Tim! Do you mind moving this discussion to the http4s/http4s project?

Sorry, the distinction between the http4s/blaze project and http4s/http4s can be confusing sometimes. Just for posterity, the blaze project is a NIO backend that doesn't satisfy the common interface http4s proper provides.
