### ISSUE TITLE
Documentation on blaze client builder configs

### ISSUE THREAD

**Issue by vangogh500** [http4s/blaze#717]
Hi in the past `BlazeClientConfig` had some documentation on the configurables:
https://http4s.org/v0.20/api/org/http4s/client/blaze/blazeclientconfig

These were super helpful for teams using this library as it gave insight into the inner workings of the client without having to do a full dive into the codebase.

Seems like the documentation was not included when moving to `BlazeClientBuilder`:
https://http4s.org/v0.20/api/org/http4s/client/blaze/blazeclientbuilder

This has been a huge pain point for us whenever someone has questions surrounding the different configurables and how they should be set up to be optimized for their own use case.

**Comment by rossabaker** [comment]
This was fixed in 04cf14d, but didn't close the ticket because it was a cherry pick.
