### ISSUE TITLE
Default Test Log Level

### ISSUE THREAD

**Issue by ChristopherDavenport** [http4s/blaze#74]
I find the default Logging Level of `trace` to be a little verbose and hard to track down what I'm looking for when I'm debugging. 

Is there a reason we keep logging so high, or could this be lowered to `info` or `debug`?

**Comment by bryce-anderson** [comment]
I'm a little confused: `trace` should be the least verbose log level of them all. https://www.slf4j.org/api/org/apache/commons/logging/Log.html

**Comment by ChristopherDavenport** [comment]
I believe your level interpretation is backwards. This generates significantly less logs in testing when set to `info` than set to `trace`.
 
`trace` shows even the least serious logs, as you increase log levels you see less logs. So trace shows all logs, debug shows all logs that are more serious that trace, info all logs that are more serious than debug etc.

**Comment by bryce-anderson** [comment]
I'm sorry: I misread your initial comment. Are you talking about the `core/src/test/resources/logback.xml` file? I'm fine with changing it to debug or info.

**Comment by rossabaker** [comment]
See how we've done it in http4s with an environment variable.  I find this convenient when troubleshooting locally: I can turn on trace when I need it, and keep Travis reasonable when I don't.
