### ISSUE TITLE
No more prereleases of  http4s-blaze-server for version 1 ?

### ISSUE THREAD

**Issue by monzonj** [http4s/blaze#775]
http4s version v1.0.0-M37 was released last September, https://http4s.org/changelog.html

However there are is no match version for http4s-blaze-server https://github.com/http4s/blaze/releases

What can we expect? is http4s M37 compatible with Blaze M36 ?

**Comment by rossabaker** [comment]
I don't see a breaking change in the changelog, but they're generally not compatible.  We should cut a release.

**Comment by rossabaker** [comment]
Should be able to release after #771 or #776.

**Comment by mrdziuban** [comment]
I've run into this as well, is there any chance of a blaze M37 release in the near future?

**Comment by rossabaker** [comment]
I'll release after #778 passes.

**Comment by rossabaker** [comment]
https://github.com/http4s/blaze/releases/tag/v1.0.0-M37 is publishing now.
