### ISSUE TITLE
Publish `0.23.14`

### ISSUE THREAD

**Issue by danicheg** [http4s/blaze#796]
There is a request from the community (in Discord 🙄) to publish `0.23.14`, so I drafted the release https://github.com/http4s/blaze/releases/edit/untagged-be436817e3539bf6813e. @rossabaker greenlit to publish it?

**Comment by rossabaker** [comment]
Go for it.  I thought I'd merged the Cats Effect 3.5 stuff, but now I remember that PoolManager needs attention.  That will have to go into an RC, but series/0.23 is clean for a regular release.

**Comment by danicheg** [comment]
https://github.com/http4s/blaze/releases/tag/v0.23.14
