### ISSUE TITLE
1.0.0-xx version compatible with CE 3.5+

### ISSUE THREAD

**Issue by aira-xite** [http4s/blaze#835]
Hello!
There is a version of blaze 0.23.x compatible with the cats-effect 3.5+. Could you please also publish `1.0.0-xx` version for the latest CE?

**Comment by aira-xite** [comment]
@rossabaker 
@danicheg 
Could you take a look, please?
It looks like a continuation of https://github.com/http4s/blaze/issues/796

**Comment by danicheg** [comment]
https://github.com/http4s/blaze/releases/tag/v1.0.0-M39
Typically, artefacts appear in Maven Central in 6-8 hours. So, stay tuned!
