### ISSUE TITLE
Blaze 0.23.15 is not compatible with Tapir 1.9.x

### ISSUE THREAD

**Issue by limansky** [http4s/blaze#847]
Hi,

  We are using blaze server 0.23.15 with tapir. I've tried to update tapir to the latest version, but faced with the issue:
  
  ```
[error] (project / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.typelevel:cats-parse_2.13:1.0.0 (early-semver) is selected over 0.3.9
[error] 	   +- org.http4s:http4s-core_2.13:0.23.24 ()             (depends on 1.0.0)
[error] 	   +- org.http4s:http4s-core_2.13:0.23.19 ()             (depends on 0.3.9)
```

It looks like `tapir-http4s-server` depends on `http4s-core` 0.23.24` when `http4s-blaze-server` depends on the earlier version. I suppose it might be safe just to add http4s-core direct dependency to our project, however may be it would be better to have a new maintenance release now? It looks like there a number of changes since the last release (at least dependencies).

**Comment by danicheg** [comment]
I think we need to publish a fresh `0.23` blaze. @rossabaker any objections?

**Comment by rossabaker** [comment]
No objections.

**Comment by rossabaker** [comment]
https://github.com/http4s/blaze/releases/tag/v0.23.16

**Comment by limansky** [comment]
thanx!
