### ISSUE TITLE
intermittent failures in 2.12 community build: 

### ISSUE THREAD

**Issue by SethTisue** [http4s/blaze#97]
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1906/consoleFull

```
[blaze] [error] Failed tests:
[blaze] [error] 	org.http4s.blaze.util.ActorSpec
[blaze] [error] Error during tests:
[blaze] [error] 	org.http4s.blaze.pipeline.stages.SerializingStageSpec
```

**Comment by SethTisue** [comment]
`ActorSpec` failure seen again at https://scala-ci.typesafe.com/view/All/job/scala-2.12.x-integrate-community-build/1953/consoleFull

**Comment by SethTisue** [comment]
`SerializingStageSpec` failed again: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1997/consoleFull

**Comment by SethTisue** [comment]
`ChannelSpec` failed again at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2014/consoleFull

this is happening often enough to be an annoyance for us. I can "solve" it at our end by disabling blaze's test suite entirely, but that's not the ideal solution. do these tests perhaps just need to have longer timeouts or something easy like that...?

**Comment by rossabaker** [comment]
@bryce-anderson, I've been leaving this for you, but I'll take a poke at it tomorrow if you're unavailable.

**Comment by rossabaker** [comment]
What is the execution model on this community build?  A lot of these tests are using a global execution context.  Is it possible any of the other projects that are running could be blocking threads, or do we have better isolation than that?  I don't see an obvious timeout to tweak, but maybe we could provide our own execution context for tests, since in isolation, this all seems to work reliably.

**Comment by SethTisue** [comment]
we only run one project at a time in the community build, so there can't be anything else happening in the same JVM.

but, it's possible for the same machine to be running a couple other jobs at the same time, so usually the only special thing is that the machine may be heavily loaded

often that merely means longer timeouts are needed, but it does sometimes reveal actual bugs that don't tend to crop up except under load

**Comment by bryce-anderson** [comment]
I can poke at this later this evening. Most of those timeouts are pretty long, `SerializationStageSpec` failed with a timeout of 10 seconds. The ActorSpec and ChannelSpec don't involve a timeout, so there seems to be some real work to do on those two.

**Comment by SethTisue** [comment]
(oops)

**Comment by SethTisue** [comment]
```
[blaze] [error] 	org.http4s.blaze.pipeline.stages.SerializingStageSpec
```

(from https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2298/consoleFull)

**Comment by SethTisue** [comment]
last call for some attention to this before I go ahead and just disable Blaze's test suite in the community build...?

one possible way to address this would be to add something that identifies certain tests as known to be flaky, then provide an environment variable or sbt setting or something that we can use to skip only those tests.  e.g. twitter-util uses `-DSKIP_FLAKY=true`

**Comment by bryce-anderson** [comment]
That code is going to be remove soon (I hope) so I'll setup a flag to disable it.

**Comment by bryce-anderson** [comment]
Some more context might be useful.

Looking closer at the log, it seems to be failing on this line: https://github.com/http4s/blaze/blob/release-0.12.x/core/src/test/scala/org/http4s/blaze/pipeline/stages/SerializingStageSpec.scala
which is from an older branch. Checking out the community build project, it seems that the build is [frozen at 0.12.4](https://github.com/scala/community-builds/blob/2.12.x/configs/project-refs.conf#L17) for the reasons described [here](https://github.com/scala/community-builds/blob/2.12.x/configs/community.dbuild#L965).

What will it take to get bumped up to the latest 0.12.x release? Could we switch to master?

**Comment by rossabaker** [comment]
I don't think master is going to fly until http4s master takes over the websockets.

**Comment by bryce-anderson** [comment]
Reading the community build wiki, it seems we need to be building whatever http4s will depend on, so that means the 0.12.x line. Based only on the times of commits, I suspect 0.12.4 was the last commit that came right from master, and the community build should be based on the `release-0.12.x` branch.

As an aside, it looks like http4s itself is being built not from the standard repo:
```
http4s-uri:                   "https://github.com/scalacommunitybuild/http4s.git#community-build-2.12"
```
The last commit of that repo dates back to August.

**Comment by SethTisue** [comment]
> the community build should be based on the release-0.12.x branch

I'll give that a try and report back.

> I'll setup a flag to disable it.

👍

**Comment by bryce-anderson** [comment]
Do you have a favorite flag name? Fwiw, I could probably backport some changes from master that should fix it, but the flag may be a good idea in general.

**Comment by SethTisue** [comment]
okay, we're tracking the release-0.12.x branch of blaze now: https://github.com/scala/community-builds/pull/648

> Do you have a favorite flag name?

heh, not really

**Comment by bryce-anderson** [comment]
`-DSKIP_FLAKY=true` it is.

**Comment by SethTisue** [comment]
(I assume this got set aside over the holidays)

**Comment by bryce-anderson** [comment]
I didn't add the flag as I believe you retargeted the build to the `release-0.12.x` branch which should include fixes for at least some of the tests. Are there more (or even the same ones) that are failing?

**Comment by SethTisue** [comment]
I haven't seen a failure lately. we can reopen this if I see one.

**Comment by bryce-anderson** [comment]
Thats fantastic. Thanks for following up, and please reopen if/when there are more failures.
